config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :ideas
  root "ideas#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
    belongs_to  :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :ideas       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:show]
  before_action :currentuser, except: [:show]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = current_user.ideas.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    if(@idea.user_id == current_user.id)
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
    else
      redirect_to ideas_path, notice: "You don't fave the facilities to this bro" 
    end  
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy = current_user.ideas.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def currentuser
    @idea != current_user.id 
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def idea_params
      params.require(:idea).permit(:title, :note, :comment, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= form_with(model: idea, local: true) do |form| %>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
        <% idea.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="bg-primary container rounded text-light">        
  <form >
    <div class="form-group">
      <%= form.label :title  ,class:"h3 mt-4"%>
      <%= form.text_field :title ,class:"form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :note ,class:"h3"%>
      <%= form.text_area :note ,class:"form-control" %>    
    </div>
    <div class="form-group">
      <%= form.label :comment ,class:"h3"%>
      <%= form.text_area :comment ,class:"form-control" %>   
    </div>
    <div class="form-group">
      <%= form.number_field :user_id ,id: :idea_user_id, type: :hidden ,value:current_user.id ,class:"form-control" %>   
    </div>
  </form> 
          

  <div class="">
    <%= form.submit class:"btn btn-light text-dark font-weight-bold mb-4 "%>
  </div>
  </div>
<% end %>
  

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>
<% if user_signed_in? %>
  <div class="container">
    <h1 class="text-primary">Weclome To The National Ideas Board</h1>
    <br>
    <table class="table table-striped table-primary table-hover">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Note</th>
          <th scope="col">Comment</th>
          <th scope="col">User id</th>
          <th scope="col" colspan="3">CRUD</th>
        </tr>
      </thead>

      <tbody>
        <% @ideas.each do |idea| %>
          
          <tr>
            <td class="h4 "><%= idea.title %></td>
            <td class="h4 "><%= idea.note %></td>
            <td class="h4 "><%= idea.comment %></td>
            <td class="h4 "><%= idea.user_id %></td>
            <td class="h4 "><%= link_to 'Show', idea %></td>
            <td class="h4 "><%= link_to 'Edit', edit_idea_path(idea) , class:"text-success" %></td>
            <td class="h4 "><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } ,class:"text-danger"%></td>
          </tr>
              
        <% end %>
        <%= current_user.id %>
      </tbody>
    </table>
  </div>

    <br>
    <button class="btn btn-primary dark">     
      <%= link_to 'New Idea', new_idea_path , class:"text-light" %>
    </button>
<% else %>
  <h1> Yo YO Go signed In first </h1>
  <%= link_to 'Sign in', new_user_session_path , class:"btn btn-primary" %>
<% end %>

app/views/ideas/new.html.erb
<div class="container mt-3">
    <h1 class="text-primary">Push a New Idea To Our Futur</h1>
    <br>
    <%= render 'form', idea: @idea %>

    <%= link_to 'Back', ideas_path , class:"mt-4 btn btn-primary text-light"%>
</div>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @idea.title %>
</p>

<p>
  <strong>Note:</strong>
  <%= @idea.note %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @idea.comment %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectTwo</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Edit user', edit_user_registration_path , class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path ,method: :delete , class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'ideas', ideas_path , class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Add idea', new_idea_path , class:"nav-link" %>
            </li>
          <% else %>
          <li class="nav-item active">
            <%= link_to 'Sign in', new_user_session_path , class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path , class:"nav-link" %>
          </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  </body>
</html>